version: '3.8'

services:
  ambassador-nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./ambassador-nginx.conf:/etc/nginx/nginx.conf
  main:
    image: nginxdemos/hello
    ports:
      - 8081:80
  canary:
    image: nginxdemos/hello
    ports:
      - 8082:80
