version: '3.8'

services:
  ambassador-nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./ambassador-nginx.conf:/etc/nginx/nginx.conf
  main:
    image: nginxdemos/hello
    ports:
      - 8081:80
  canary:
    image: nginxdemos/hello
    ports:
      - 8082:80
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.9.0
    ports:
      - 9113:9113
    command: -nginx.scrape-uri=http://ambassador-nginx/stub_status
    depends_on:
      - ambassador-nginx
    links:
      - ambassador-nginx
